### ISSUE TITLE
Consider using Google's Java style guide + tools

### ISSUE THREAD

**Issue by ajvb** [mozilla-services/foxsec-pipeline#12]
Style Guide: https://google.github.io/styleguide/javaguide.html
CLI tool: https://github.com/google/google-java-format
Vim plugin: https://github.com/google/vim-codefmt

I have no strong feelings about this style guide, but it would be nice to be able to use the vim plugin to support automatic and consistent formatting.

**Comment by psiinon** [comment]
FYI for ZAP we're moving to https://github.com/diffplug/spotless
Seems to be working well for us so far but YMMV

**Comment by ameihm0912** [comment]
@ajvb @psiinon yeah great idea and thanks for the info

I added maven configuration for the spotless plugin to run in travis.

Also mention of style and codefmt setup instructions [here](https://github.com/mozilla-services/foxsec-pipeline/blob/master/CONTRIBUTING.md).
