### ISSUE TITLE
Persist ALL events somewhere (e.g. BigQuery)

### ISSUE THREAD

**Issue by adrianosela** [mozilla-services/foxsec-pipeline#229]
We aren't persisting anything outside of the built-in persistence options of the data sources we read from.

Fulfilling this issue involves storing all generic events somewhere

**Comment by ameihm0912** [comment]
@adrianosela this is an architectural change that will be fairly involved; I am closing this issue for now until we have had a chance to discuss the approach and we will recreate it with the requirements for this once we have them

**Comment by adrianosela** [comment]
Gotcha. Just wanted to make sure I was persisting GuardDuty events somehow before my departure, however if you're planning on implementing this in a way that doesnt require changes to individual pipelines I guess it is no longer my duty to get this done before then. @ameihm0912
