### ISSUE TITLE
Improve AMO cloud submission alert summary

### ISSUE THREAD

**Issue by ameihm0912** [mozilla-services/foxsec-pipeline#371]
Improve summary to include add-on GUID

Depends on https://github.com/mozilla/addons-server/issues/13942

**Comment by diox** [comment]
mozilla/addons-server#13942 is now live in production.

This means, you can use the following log message to detect submissions: 
```'New version: %r (%s) from %r' % (version, version.id, upload)```

With:
- `version` (**string**, representation of the version object uploaded. Should look like `<Version: %s>`, where `%s` is the version number)
- `version.id` (**integer** version ID in the `versions` table)
- `upload` (**string**, representation of the File Upload uploaded. Should look like `<FileUpload: %s>` where `%s` is the upload UUID)

More importantly for foxsec pipeline, the following extra fields are present:
- `email` (**string** user email)
- `user_id` (**integer** user ID in the `users` table)
- `guid` (**string** extension identifier)
- `from_api` (**boolean** indicating whether or not the upload was made using the API)
- `uid` (**string** username in the `users` table, but *do not use it*, it's not currently reliable for this particular situation. It's likely to always contain `<anon>` for API requests at this time)
- `remoteAddressChain` (**string** IP address used by submission request)

For reference, the old log you are currently using if I'm not mistaken is:
```'UPLOAD: %r (%s bytes) to %r' % (filename, size, loc)``` with `email` as the extra field being sent.

Unless you do something with the parameters that log sends, I'd suggest you stop using it and use the one I've described above. If you are using those parameters for something, let me know and I can look into adding them as well, though I don't think they are particularly relevant (logging the addon `guid` is much more useful to us to find them afterwards).
