### ISSUE TITLE
Create shared helper for reading config files from gcs

### ISSUE THREAD

**Issue by kkleemola** [mozilla-services/foxsec-pipeline#378]
Refactor pattern for reading file from gcs or resource path into a helper that can be used everytime we need to do this.

**Comment by ameihm0912** [comment]
@kkleemola we have this here:

https://github.com/mozilla-services/foxsec-pipeline/blob/097a431054dd27188ebcc6d6a5ab3edf87a8417b/src/main/java/com/mozilla/secops/FileUtil.java

That will always return an `ArrayList` though, so maybe something a bit more generic is needed to cover all possible cases.
