### ISSUE TITLE
Improve alert batching for GuardDuty (within Gatekeeper)

### ISSUE THREAD

**Issue by ajvb** [mozilla-services/foxsec-pipeline#503]
There are cases where we may get multiple alerts of the same type that we would want to page on (via Pagerduty). An example of this is if someone is using the root credentials we can get many variations on the "RootCredentialUsage" alert.

We should improve the ability to batch by alert type within https://github.com/mozilla-services/foxsec-pipeline/blob/50d2c02f078a6a279b103bcb68875c7d7bc6ab0d/src/main/java/com/mozilla/secops/gatekeeper/GuardDutyTransforms.java#L272 for these cases.

This is specifically important for alerts that page, so might be worth adding this functionality to [GuardDutyFindingMatcher](https://github.com/mozilla-services/foxsec-pipeline/blob/master/src/main/java/com/mozilla/secops/gatekeeper/GuardDutyFindingMatcher.java)

**Comment by kkleemola** [comment]
Closing as Gatekeeper is no longer being used.
