### ISSUE TITLE
Update AMO event to match new logging statement

### ISSUE THREAD

**Issue by diox** [mozilla-services/foxsec-pipeline#510]
Some time ago we (AMO engineers) accidentally removed a log statement foxsec-pipeline was using when an user logged in from FxA. I'm going to add it back in https://github.com/mozilla/addons-server/pull/16377/files, with a reworded string to make it more explicit, and only the minimal info needed.

foxsec-pipeline needs to be updated for the new string. Specifically, this:
https://github.com/mozilla-services/foxsec-pipeline/blob/af86e371cc6f3d371da60fb9a8c83f29f4b2daa0/src/main/java/com/mozilla/secops/parser/AmoDocker.java#L17

Needs to change to match this:
`Logging in FxA user %s` where `%s` is the email.

**Comment by kkleemola** [comment]
Updated. Thanks!
